### ISSUE TITLE
Quick Start: scientists route model error

### ISSUE THREAD

**Issue by belgoros** [ember-learn/guides-source#1241]
Following the quick-start guide, when adding the `model` hook to the `scientists` route, I got the syntax error:
![Screen Shot 2019-12-26 at 12 41 48](https://user-images.githubusercontent.com/83579/71474765-465d5980-27dd-11ea-899c-565c478897ff.png)
Some more stack trace looks as follows:
```
(node:795) UnhandledPromiseRejectionWarning: SyntaxError: /Users/serge-mac/Development/ember/ember-quickstart/ember-quickstart/routes/scientists.js: Unexpected token (4:9)

  2 | 
  3 | export default class ScientistsRoute extends Route {
> 4 |   return ['Marie Curie', 'Mae Jemison', 'Albert Hofmann'];
    |          ^
  5 | }
  6 | 
    at Parser.raise (/Users/serge-mac/Development/ember/ember-quickstart/node_modules/@babel/parser/lib/index.js:7012:17)
    at Parser.unexpected (/Users/serge-mac/Development/ember/ember-quickstart/node_modules/@babel/parser/lib/index.js:8405:16)
    at Parser.parseClassMemberWithIsStatic (/Users/serge-mac/Development/ember/ember-quickstart/node_modules/@babel/parser/lib/index.js:11639:12)
```
Reproduced with:
```
ember-cli: 3.15.1
node: 12.14.0
os: darwin x64
```
More of that, the path to the error is not correct, -
```
(node:1188) UnhandledPromiseRejectionWarning: SyntaxError: 
.../ember/ember-quickstart/ember-quickstart/routes/scientists.js: Unexpected token (4:9)
```
contains `ember-quickstart` twice, instead of being:
```
(node:1188) UnhandledPromiseRejectionWarning: SyntaxError: 
...ember/ember-quickstart/app/routes/scientists.js: Unexpected token (4:9)
```
but it is rather a Node.js issue, I think.

**Comment by belgoros** [comment]
My bad, I forgot to put inside the `model` :(
