### ISSUE TITLE
Figure out why search is slightly broken

### ISSUE THREAD

**Issue by jenweber** [ember-learn/guides-source#1300]
Running a search for Ember.js has the following error, which you can see if you go to the 3.16 guides and try to search for something like "computed":

```
Uncaught (in promise) TypeError: Cannot read property 'title' of undefined
    at r.<anonymous> (ember-guides-a59c00095b64c04983040bc2645c0b55.js:47)
    at vendor-6d6baade7e96df5ca07494ff39737804.js:1170
    at te (vendor-6d6baade7e96df5ca07494ff39737804.js:1017)
    at r.o.get (vendor-6d6baade7e96df5ca07494ff39737804.js:1170)
    at r.c.get [as sectionTitle] (vendor-6d6baade7e96df5ca07494ff39737804.js:996)
    at se (vendor-6d6baade7e96df5ca07494ff39737804.js:1033)
    at vendor-6d6baade7e96df5ca07494ff39737804.js:303
    at J (vendor-6d6baade7e96df5ca07494ff39737804.js:1015)
    at r.n.compute (vendor-6d6baade7e96df5ca07494ff39737804.js:303)
    at r.value (vendor-6d6baade7e96df5ca07494ff39737804.js:295)
```

During `ember deploy production`, this error was in the console:

```
Error while processing route: version.show Cannot read property 'pages' of undefined TypeError: Cannot read property 'pages' of undefined
    at /var/folders/9k/l7x9d45s373_nchwp07mkrqr0000gn/T/broccoli-28608f39YzLeY4J3T/out-492-uglify_writer/assets/ember-guides.js:145:27
    at r.model (/var/folders/9k/l7x9d45s373_nchwp07mkrqr0000gn/T/broccoli-28608f39YzLeY4J3T/out-492-uglify_writer/assets/ember-guides.js:145:122)
    at r.s.deserialize (/var/folders/9k/l7x9d45s373_nchwp07mkrqr0000gn/T/broccoli-28608f39YzLeY4J3T/out-492-uglify_writer/assets/vendor.js:1469:131)
    at t.getModel (/var/folders/9k/l7x9d45s373_nchwp07mkrqr0000gn/T/broccoli-28608f39YzLeY4J3T/out-492-uglify_writer/assets/vendor.js:3796:26)
    at /var/folders/9k/l7x9d45s373_nchwp07mkrqr0000gn/T/broccoli-28608f39YzLeY4J3T/out-492-uglify_writer/assets/vendor.js:3776:215
    at w (/var/folders/9k/l7x9d45s373_nchwp07mkrqr0000gn/T/broccoli-28608f39YzLeY4J3T/out-492-uglify_writer/assets/vendor.js:3957:12)
    at _ (/var/folders/9k/l7x9d45s373_nchwp07mkrqr0000gn/T/broccoli-28608f39YzLeY4J3T/out-492-uglify_writer/assets/vendor.js:3955:128)
    at t.invokeWithOnError (/var/folders/9k/l7x9d45s373_nchwp07mkrqr0000gn/T/broccoli-28608f39YzLeY4J3T/out-492-uglify_writer/assets/vendor.js:3491:242)
    at e.t.flush (/var/folders/9k/l7x9d45s373_nchwp07mkrqr0000gn/T/broccoli-28608f39YzLeY4J3T/out-492-uglify_writer/assets/vendor.js:3483:74)
    at e.t.flush (/var/folders/9k/l7x9d45s373_nchwp07mkrqr0000gn/T/broccoli-28608f39YzLeY4J3T/out-492-uglify_writer/assets/vendor.js:3497:207)
    at e.r._end (/var/folders/9k/l7x9d45s373_nchwp07mkrqr0000gn/T/broccoli-28608f39YzLeY4J3T/out-492-uglify_writer/assets/vendor.js:3559:9)
    at _boundAutorunEnd (/var/folders/9k/l7x9d45s373_nchwp07mkrqr0000gn/T/broccoli-28608f39YzLeY4J3T/out-492-uglify_writer/assets/vendor.js:3509:574)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Comment by jenweber** [comment]
Thank you to lifeart for debugging! I'm going to open a PR to fix this.

<img width="757" alt="Screen Shot 2020-02-12 at 5 51 15 PM" src="https://user-images.githubusercontent.com/16627268/74384905-4a126300-4dc0-11ea-884a-ef36558c1f9e.png">
